trigger:
- main

name: 0.0.$(Rev:r) # Build Number

pool:
  vmImage: 'ubuntu-20.04'

steps:
- script: echo $(Build.BuildNumber)

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 3.1.x

- script: dotnet restore --packages .nuget/packages
  displayName: 'Restore Packages'

- script: dotnet build --configuration Release --no-restore
  displayName: 'Build Solution'

- script: dotnet publish --configuration Release
    --runtime linux-x64 --version-suffix $(Build.BuildNumber)
    --output ./publish --no-restore
  displayName: 'Publish Solution'

- script: docker build -t containerregistry99.azurecr.io/mytelegrambot:$(Build.BuildNumber) .
  displayName: 'Bake Docker Image'

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: 'Container Registry Connection'

- script: docker image push $(dockerImageTag)
  displayName: 'Push Docker Image'

- task: Docker@2
  displayName: Logout of ACR
  inputs:
    command: logout
    containerRegistry: 'Container Registry Connection'
